# Generated by Django 4.2.7 on 2023-11-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='товар')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='товар')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
                ('image', models.ImageField(max_length=1000, upload_to='картинки')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('price', models.CharField(max_length=150, verbose_name='цена')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_last_use', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('name',),
            },
        ),
    ]
